### ISSUE TITLE
Add Sonic Runners Revival to Community Source

### ISSUE THREAD

**Issue by e10withadot** [SideStore/Community-Source#11]
Source: https://assets.sonicrunners.com/srr223.ipa

![image](https://user-images.githubusercontent.com/91983480/211245466-b2926309-e204-4e8d-b187-9a11710ba117.jpeg)

![1ABC1E14-51A3-414E-8F0D-9C411BFD61DD](https://user-images.githubusercontent.com/91983480/211245660-d30904ed-8ae3-4803-8754-a123c5d8c507.png)

![086DE805-B9EC-4AD2-8650-71DFF3CD8C87](https://user-images.githubusercontent.com/91983480/211245665-0c2441d0-f25c-4917-afb8-31077a622785.png)

![BD3BE4DB-B6C2-4088-AFEE-E286EB001C3E](https://user-images.githubusercontent.com/91983480/211245668-bde931c5-9531-4bfb-a9c7-83861f2ff2cd.png)

![6EA724D9-67FC-4D87-92AE-56AD60EA101C](https://user-images.githubusercontent.com/91983480/211245673-bbab16d0-766b-4f10-b77d-9eb9105c6ca4.png)

Sonic Runners Revival is a fan server for the now-discontinued Sonic Runners, a F2P auto-runner developed by Sonic Team, and first launched in 2015. It features many beloved characters from the series, and even many obscure ones.

You progress through level chunks by running automatically, and jumping with correct timing. Like in 2D Sonic, higher paths are faster and gain more rewards.

The game has a story mode, where you progress through a mission-based narrative and run the required amount for each mission- and timed mode, which has you run while a timer runs out, forcing you to look for stopwatches to keep going.

The game’s in-app purchases have been removed/repurposed, and it still gets frequently updated and supported by the community.

**Comment by polymo1** [comment]
Closing for pirated/copyrighted material.
