### ISSUE TITLE
Add yattee to community source and trusted sources

### ISSUE THREAD

**Issue by lonkelle** [SideStore/Community-Source#3]
Source Link:  https://raw.githubusercontent.com/yattee/repos/main/alt/apps.json

**Comment by lonkelle** [comment]
@Spidy123222 Do you have the ability to set a status on this ticket?

**Comment by Spidy123222** [comment]
Not sure what you mean but this should solve this. https://github.com/SideStore/SideStore/pull/200

**Comment by lonkelle** [comment]
I merged that. Thanks! Can we add it to the parser or does the parser already automatically take all the trusted sources and grabs their apps?

As for can you change the status of this issue's project, I mean the sidebar of the issue:

![Screenshot 2022-12-25 at 5 43 27 AM](https://user-images.githubusercontent.com/5572600/209464893-d4f1aa07-9c95-4b8c-8ae1-22c883170747.jpg)

**Comment by Spidy123222** [comment]
> I merged that. Thanks! Can we add it to the parser or does the parser already automatically take all the trusted sources and grabs their apps?
> 
> 
> 
> As for can you change the status of this issue's project, I mean the sidebar of the issue:
> 
> 
> 
> ![Screenshot 2022-12-25 at 5 43 27 AM](https://user-images.githubusercontent.com/5572600/209464893-d4f1aa07-9c95-4b8c-8ae1-22c883170747.jpg)
> 
> 
> 
> 

There is no need to use the communist store parser as it's added to trusted sources. Community store is meant for apps not in trusted sources or devs with lots of sources. I belive I can, just I don't think I have anything I should change it to.

**Comment by lonkelle** [comment]
I changed this to done, since it's done.
