### ISSUE TITLE
Add `Anime Now`

### ISSUE THREAD

**Issue by bachig26** [SideStore/Community-Source#6]
Repo: https://github.com/AnimeNow-Team/AnimeNow

#### Description:
Anime Now is an iOS and macOS app built with SwiftUI and TCA, which is used to watch anime.
     
#### Requirement:
Requires at least iOS 14, iPadOS 14, and macOS 11 or later.

**Comment by Spidy123222** [comment]
I am sorry but this seems to provide copyrighted material via the app and we want to not have pirated content on the store.
